-- =============================================================
-- V1__initial_schema.sql
-- Baseline schema representing the full current state of the DB.
-- Managed by Flyway. DO NOT edit this file after it has been run.
-- For changes, create V2__description.sql, V3__description.sql, etc.
-- =============================================================

-- -------------------------
-- TABLE: users
-- -------------------------
CREATE TABLE IF NOT EXISTS users (
    id       VARCHAR(255) PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(50)  NOT NULL  -- enum: user, admin
);

-- -------------------------
-- TABLE: products
-- -------------------------
CREATE TABLE IF NOT EXISTS products (
    id            VARCHAR(255)   PRIMARY KEY,
    name          VARCHAR(255)   NOT NULL,
    price         NUMERIC(19, 2) NOT NULL,
    category      VARCHAR(50)    NOT NULL,  -- enum: Electronics, Clothing, Home, Books, Sports
    stock         INTEGER        NOT NULL,
    rating        DOUBLE PRECISION,
    rating_count  INTEGER,
    description   TEXT
);

-- -------------------------
-- TABLE: product_images  (@ElementCollection on Product.images)
-- -------------------------
CREATE TABLE IF NOT EXISTS product_images (
    product_id VARCHAR(255) NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    image_url  VARCHAR(255)
);

-- -------------------------
-- TABLE: product_specs  (@ElementCollection on Product.specs)
-- -------------------------
CREATE TABLE IF NOT EXISTS product_specs (
    product_id VARCHAR(255) NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    spec_key   VARCHAR(255) NOT NULL,
    spec_value VARCHAR(255),
    PRIMARY KEY (product_id, spec_key)
);

-- -------------------------
-- TABLE: reviews
-- -------------------------
CREATE TABLE IF NOT EXISTS reviews (
    id         VARCHAR(255) PRIMARY KEY,
    product_id VARCHAR(255) NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    user_name  VARCHAR(255),
    rating     INTEGER,
    title      VARCHAR(255),
    body       TEXT,
    created_at TIMESTAMP
);

-- -------------------------
-- TABLE: orders
-- Embedded Address (shipping/billing) and PaymentInfo columns are flattened here
-- -------------------------
CREATE TABLE IF NOT EXISTS orders (
    id                    VARCHAR(255)   PRIMARY KEY,
    user_id               VARCHAR(255)   NOT NULL,
    status                VARCHAR(50)    NOT NULL,  -- enum: pending, shipped, delivered, cancelled
    created_at            TIMESTAMP,
    subtotal              NUMERIC(19, 2),
    discount              NUMERIC(19, 2),
    tax                   NUMERIC(19, 2),
    total                 NUMERIC(19, 2),

    -- Embedded: shipping Address
    shipping_full_name    VARCHAR(255),
    shipping_email        VARCHAR(255),
    shipping_phone        VARCHAR(255),
    shipping_address1     VARCHAR(255),
    shipping_city         VARCHAR(255),
    shipping_state        VARCHAR(255),
    shipping_zip          VARCHAR(255),
    shipping_country      VARCHAR(255),

    -- Embedded: billing Address
    billing_full_name     VARCHAR(255),
    billing_email         VARCHAR(255),
    billing_phone         VARCHAR(255),
    billing_address1      VARCHAR(255),
    billing_city          VARCHAR(255),
    billing_state         VARCHAR(255),
    billing_zip           VARCHAR(255),
    billing_country       VARCHAR(255),

    -- Embedded: PaymentInfo
    card_name             VARCHAR(255),
    card_number           VARCHAR(255),
    exp                   VARCHAR(255),
    cvc                   VARCHAR(255)
);

-- -------------------------
-- TABLE: order_items
-- -------------------------
CREATE TABLE IF NOT EXISTS order_items (
    id         VARCHAR(255)   PRIMARY KEY,
    order_id   VARCHAR(255)   NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id VARCHAR(255)   NOT NULL,
    name       VARCHAR(255)   NOT NULL,
    price      NUMERIC(19, 2) NOT NULL,
    qty        INTEGER        NOT NULL
);

-- -------------------------
-- TABLE: refresh_token
-- -------------------------
CREATE TABLE IF NOT EXISTS refresh_token (
    id          BIGSERIAL    PRIMARY KEY,
    user_id     VARCHAR(255) UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    token       VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP    NOT NULL
);

